name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: "pytest on ${{ matrix.os }} / py${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        shell: bash
        run: |
          python -m pip install -U pip setuptools wheel
          if [ -f requirements.lock.txt ]; then
            pip install -r requirements.lock.txt
          else
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
          fi

      - name: Run tests
        shell: bash
        run: |
          python -m pytest -q

      - name: Sanity run (no plot)
        shell: bash
        run: |
          python main.py --cases DOCS/validation_cases.yaml --outdir results
